name: kunmeti kaj alŝuti retejon
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  kunmeto:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo DEBIAN_FRONTEND=noninteractive apt-get install -y jekyll
      - run: jekyll build
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: _site
          retention-days: 1
  alsxuto:
    runs-on: ubuntu-22.04
    needs: kunmeto
    steps:
      - uses: actions/download-artifact@v3
      - uses: mschmitt/rsync-with-ssh-agent@v2
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: c3eo.chaotik.de
          RSYNC_LOCAL_PATH: '_site/'
          RSYNC_OPTIONS: '--recursive --exclude .well-known --delete --verbose'
