name: build and upload site
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: gem install bundler jekyll
      - run: make
#      - uses: mschmitt/rsync-with-ssh-agent@v2
#       with:
#          SSH_KEY: ${{ secrets.SSH_KEY }}
#          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
#          SSH_USER: martin
#          SSH_HOST: c3eo.chaotik.de
#          RSYNC_LOCAL_PATH: 'site/'
#          RSYNC_OPTIONS: '--exclude ".*" --recursive --delete-excluded --verbose'
